// Default data and initial state for the app
import { AppData, MaintenanceTask, Achievement, ComponentCheck } from '@/types';

export const defaultMaintenanceTasks: MaintenanceTask[] = [
  {
    id: 'wash-1',
    type: 'wash',
    name: 'Wash Motorcycle',
    description: 'Full motorcycle wash and cleaning',
    frequency: 30, // monthly
    lastCompleted: null,
    nextDue: null,
    completed: false,
    streak: 0,
  },
  {
    id: 'chain-lube-1',
    type: 'chain_lube',
    name: 'Chain Lubrication',
    description: 'Apply chain lube to keep it running smooth',
    frequency: 14, // bi-weekly
    lastCompleted: null,
    nextDue: null,
    completed: false,
    streak: 0,
  },
  {
    id: 'chain-clean-1',
    type: 'chain_clean',
    name: 'Chain Cleaning',
    description: 'Deep clean the chain',
    frequency: 14, // bi-weekly
    lastCompleted: null,
    nextDue: null,
    completed: false,
    streak: 0,
  },
];

export const defaultComponentChecks: ComponentCheck[] = [
  {
    id: 'comp-1',
    name: 'Engine Oil',
    category: 'fluids',
    status: 'good',
    lastChecked: null,
    notes: '',
  },
  {
    id: 'comp-2',
    name: 'Brake Pads',
    category: 'brakes',
    status: 'good',
    lastChecked: null,
    notes: '',
  },
  {
    id: 'comp-3',
    name: 'Tire Pressure',
    category: 'tires',
    status: 'good',
    lastChecked: null,
    notes: '',
  },
  {
    id: 'comp-4',
    name: 'Headlight',
    category: 'lights',
    status: 'good',
    lastChecked: null,
    notes: '',
  },
  {
    id: 'comp-5',
    name: 'Coolant Level',
    category: 'fluids',
    status: 'good',
    lastChecked: null,
    notes: '',
  },
];

export const defaultAchievements: Achievement[] = [
  {
    id: 'ach-1',
    name: 'First Ride',
    description: 'Log your first kilometer',
    icon: '🏍️',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 1,
    category: 'mileage',
  },
  {
    id: 'ach-2',
    name: 'Century Club',
    description: 'Ride 100 kilometers',
    icon: '💯',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 100,
    category: 'mileage',
  },
  {
    id: 'ach-3',
    name: 'Thousand Miles',
    description: 'Ride 1000 kilometers',
    icon: '🌟',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 1000,
    category: 'mileage',
  },
  {
    id: 'ach-4',
    name: 'Clean Machine',
    description: 'Wash your bike 5 times',
    icon: '✨',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 5,
    category: 'maintenance',
  },
  {
    id: 'ach-5',
    name: 'Chain Master',
    description: 'Lube chain 10 times',
    icon: '⛓️',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 10,
    category: 'maintenance',
  },
  {
    id: 'ach-6',
    name: 'Safety First',
    description: 'Complete all component checks',
    icon: '🔧',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 5,
    category: 'maintenance',
  },
  {
    id: 'ach-7',
    name: 'Gear Up',
    description: 'Add 3 riding gear items to wishlist',
    icon: '🧥',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 3,
    category: 'gear',
  },
  {
    id: 'ach-8',
    name: 'Fully Equipped',
    description: 'Own all essential riding gear',
    icon: '🎯',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 5,
    category: 'gear',
  },
  {
    id: 'ach-9',
    name: 'Maintenance Streak',
    description: 'Complete maintenance 7 days in a row',
    icon: '🔥',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 7,
    category: 'special',
  },
  {
    id: 'ach-10',
    name: 'Road Warrior',
    description: 'Ride 5000 kilometers',
    icon: '⚡',
    unlocked: false,
    unlockedAt: null,
    progress: 0,
    target: 5000,
    category: 'mileage',
  },
];

export const defaultAppData: AppData = {
  maintenanceTasks: defaultMaintenanceTasks,
  componentChecks: defaultComponentChecks,
  mileageEntries: [],
  achievements: defaultAchievements,
  ridingGear: [],
  calendarEvents: [],
  totalKilometers: 0,
  bikeModel: 'My Bike',
  bikeYear: new Date().getFullYear(),
};

